# ===================================
#  Relation Behavior Config
# ===================================

states:
    label: winter.location::lang.state.label
    list: ~/plugins/winter/location/models/state/columns.yaml
    form: ~/plugins/winter/location/models/state/fields.yaml
    view:
        showSearch: true
        toolbarPartial: $/winter/location/controllers/locations/_states_list_toolbar.htm
        filter: $/winter/location/models/state/filters.yaml
